export function nameCardSwitch(code: string) {
  switch (code) {
    case 'AC': return 'Às de Paus'
    case '2C': return 'Dois de Paus'
    case '3C': return 'Três de Paus'
    case '4C': return 'Quatro de Paus'
    case '5C': return 'Cinco de Paus'
    case '6C': return 'Seis de Paus'
    case '7C': return 'Sete de Paus'
    case '8C': return 'Oito de Paus'
    case '9C': return 'Nove de Paus'
    case '0C': return 'Dez de Paus'
    case 'JC': return 'Valete de Paus'

    case 'AD': return 'Às de Ouros'
    case '2D': return 'Dois de Ouros'
    case '3D': return 'Três de Ouros'
    case '4D': return 'Quatro de Ouros'
    case '5D': return 'Cinco de Ouros'
    case '6D': return 'Seis de Ouros'
    case '7D': return 'Sete de Ouros'
    case '8D': return 'Oito de Ouros'
    case '9D': return 'Nove de Ouros'
    case '0D': return 'Dez de Ouros'
    case 'JD': return 'Valete de Ouros'

    case 'AS': return 'Às de Espadas'
    case '2S': return 'Dois de Espadas'
    case '3S': return 'Três de Espadas'
    case '4S': return 'Quatro de Espadas'
    case '5S': return 'Cinco de Espadas'
    case '6S': return 'Seis de Espadas'
    case '7S': return 'Sete de Espadas'
    case '8S': return 'Oito de Espadas'
    case '9S': return 'Nove de Espadas'
    case '0S': return 'Dez de Espadas'
    case 'JS': return 'Valete de Espadas'

    case 'AH': return 'Às de Copas'
    case '2H': return 'Dois de Copas'
    case '3H': return 'Três de Copas'
    case '4H': return 'Quatro de Copas'
    case '5H': return 'Cinco de Copas'
    case '6H': return 'Seis de Copas'
    case '7H': return 'Sete de Copas'
    case '8H': return 'Oito de Copas'
    case '9H': return 'Nove de Copas'
    case '0H': return 'Dez de Copas'
    case 'JH': return 'Valete de Copas'
    default: return ''
  }
}
